version: "2"
services:
  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - $MYSQL_LISTEN_PORT:3306
    volumes:
      - ./mysql/db:/var/lib/mysql_data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - $PHPMYADMIN_LISTEN_PORT:80
    volumes:
      - ./phpmyadmin/sessions:/var/lib/php7/session
    depends_on: 
      - mysql

  apache:
    env_file: .env
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - $APACHE_LISTEN_PORT:80
    volumes:
      - $PUBLIC_DIR:/var/www/html
      - ./apache2/sites-available:/etc/apache2/sites-available
    depends_on: 
      - mysql
